### ISSUE TITLE
CSS 相关问题

### ISSUE THREAD

**Issue by ZhangHang12135** [ZhangHang12135/ZhangHang12135.github.io#4]
**1. 如何隐藏元素？**
```css
display: none; // 元素消失，不占据空间，无交互，存在dom
visibility: hidden; // 元素不可见，但占据文档空间，无交互
opacity： 0； // 透明不可见，占据空间，可交互
width:0; // 无barder,padding情况，不占据空间，一般不可交互
```

**Comment by ZhangHang12135** [comment]
**2. 盒子模型**
标准模型：width = content。width就是内容的宽度
ie模型： width = conetent +padding + border。width 的宽度包含padding + border的宽度
box-sizing: content-box | border-box

**Comment by ZhangHang12135** [comment]
**3. 选择器**
严格来讲只有三种，id选择器，类选择器，标签选择器。
所谓的后代选择器，群组选择器，都是这三种的扩展。
描述越准确优先级越高。id>类>标签
!important > 内联 > id

**Comment by ZhangHang12135** [comment]
**4. 说说em/px/rem/vh/vw区别?**
em 是相对单位，相对于当前的字体大小来计算的，
rem 就是相对html的字体大小计算，一般为16px
px就是像素点
vh 和vw 是一类，高度的百分比，宽度的百分比。在桌面端是浏览器可视区域，移动端是布局视口。%是相对于广义上父元素。

**Comment by ZhangHang12135** [comment]
**5. BFC的理解**
块级格式化上下文。可以理解为独立容器。容器和容器之间的布局不会相互影响。
html是最大的BFC, 其它的可以用css来创建。
1. float浮动
2. 绝对定位的元素 position:fixed
3. overflow 不为 visible的
4. flex, 网格等
5. 当然最新的就是用 display:flow-root显示创建BFC

解决高度坍缩问题（浮动），解决外边距重合问题。

**Comment by ZhangHang12135** [comment]
**6. 层叠上下文**
简单理解就是z-index, 以父元素为基准，比较同层。如果父元素低，那其所有的子元素都会低

**Comment by ZhangHang12135** [comment]
**7. 元素居中**
```css
display: flex;
justify-content:center;
aligin-items:center;
````

**Comment by ZhangHang12135** [comment]
**8. 两栏布局？三栏布局？**
```css
// float
.bos:{
    display: flow-root;// 防止高度塌陷。
}
.left {
    float: left;
    width: 200px;
}
.right {
    margin-left: 200px
}

// flex
.box {
    display: flex;
}
.left: {
    width:200px;
}
.right {
    flex:1'
}
```
